---
title: "Evaluate Functions"
output: html_notebook
---
Aktuellste Paketversion installieren und laden
```{r}
library(devtools)
install_github("https://github.com/TimoSchuer/ExmaraldaR", force = TRUE)
library(ExmaraldaR)
library(xml2)
library(dplyr)
```

Testdatei festlegen
```{r}
path <- choose.files()
path
file <- xml2::read_xml(path, encoding="UTF-8")
```


Gesamtzeit

```{r}
start <- Sys.time()
test <- read_exb_file(path=path, readAnn = FALSE)
end <- Sys.time()
time <- start-end
time
```
Benchmarking Werte: Zeit pro Transkriptionsevent, Zeit pro Annotationsevent, Zeit pro Events (Gesamt)
```{r}

```
Zeiten der einzelnen Funktionen ermitteln: read_timeline
```{r}
startTimeline <- Sys.time()
timeline <- read_timeline(file)
endTimeline <- Sys.time()
timeTimeline <- endTimeline-startTimeline
timeTimeline
```
Read_events
```{r}
start <- Sys.time()
events <- read_events(file, path)
end <- Sys.time()
timeReadEvents <- end-start
timeReadEvents
```
sort_events
```{r}
start <- Sys.time()
events_sorted <- sort_events(events, timeline)
end <- Sys.time()
timeSortEvents <- end-start
timeSortEvents
```

